### ISSUE TITLE
bind:cannot assign requested address

### ISSUE THREAD

**Issue by Alsen57** [svenstaro/ssl-proxy-docker#2]
Hi,

when ever i am using the dockerized version from you i get the same mistake when trying following:

docker run -p 443:443 -from ip:443 -to ip:8501  

i get the error message: bind cannot assign requested address. But when i am using the .exe version from  the console from https://github.com/suyashkumar/ssl-proxy it is working. 

I had a look into TCP view to check if the port is in use but it is not. Do you have an idea what could occure the error when using the docker version?

Thanks in advance!

**Comment by svenstaro** [comment]
I don't really maintain this anymore and should probably archive it. I wrote [proxyboi](https://github.com/svenstaro/proxyboi) as a better replacement.

**Comment by Alsen57** [comment]
Hi thanks for the fast response. Does proxyboi work the same way? So that you do not have to use domain names but can use directly the ip adress?

**Comment by svenstaro** [comment]
Well, give it a spin and see whether it works the way you expect. Let's close this and continue support in the actual proxyboi repo.
